class_path: cmap.ml.classifiers.Classifier
init_args:
  encoder:
    class_path : cmap.ml.encoders.TransformerEncoder
    init_args:
      position_encoder: 
        class_path: cmap.ml.embeddings.position.PositionalEncoding
        init_args: 
          d_model: 256
          tau: 10000
          max_len: 10000
      bands_encoder:
        class_path: cmap.ml.embeddings.bands.PixelEncoding
        init_args:
          sizes:
            - 9
            - 32
            - 64
            - 128
            - 256
      d_model: 256
      n_att_head: 8
      n_att_layers: 4
      dropout_p: 0.1
  decoder:
    class_path: cmap.ml.decoders.MulticlassClassification
    init_args:
      hidden: 256
      num_classes : 7
  min_lr : 0.00001
  max_lr : 0.0001
  classes_weights:
    other : 0.52
    ble_tendre : 0.52
    mais : 0.66
    orge : 1.12
    colza : 2.64
    tournesol : 3.25
    ble_dur : 13.00
