version: '3.1'
services:
  db:
    image: postgres
    restart: alwaysa
    environment:
      POSTGRES_PASSWORD: cmap2023
      POSTGRES_USER: michel
      POSTGRES_DB: crops
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /mnt/sda/geowatch/datasets/hackathon/crop_mapping/pgdata:/var/lib/postgresql/data/pgdata

