trainer:
  callbacks: 
      class_path: pytorch_lightning.callbacks.LearningRateMonitor
  max_epochs: 100
  precision: 16-mixed
data:
  class_path: cmap.data.modules.SITSDataModule
  init_args:
    root: /mnt/sda/geowatch/datasets/hackathon/crop_mapping/small
    include_temperatures: true 
    num_workers: 1
    batch_size: 128
    train_seasons:
      - 2019
      - 2020
    val_seasons:
      - 2021
    classes:
      - other
      - ble_dur
      - ble_tendre
      - mais
      - orge
      - colza
      - tournesol
model:
  class_path: cmap.ml.classifiers.Classifier
  init_args:
    encoder:
      class_path : cmap.ml.encoders.TransformerEncoder
      init_args:
        position_encoder: 
          class_path: cmap.ml.embeddings.position.PositionalEncoding
          init_args: 
            d_model: 256
            tau: 10000
            max_len: 10000
        bands_encoder:
          class_path: cmap.ml.embeddings.bands.PixelEncoding
          init_args:
            sizes:
              - 9
              - 32
              - 64
              - 128
              - 256
        d_model: 256
        n_att_head: 8
        n_att_layers: 4
        dropout_p: 0.1
    decoder:
      class_path: cmap.ml.decoders.MulticlassClassification
      init_args:
        hidden: 256
        num_classes : 7
    min_lr : 0.00001
    max_lr : 0.0001
