trainer:
  callbacks: 
      class_path: pytorch_lightning.callbacks.LearningRateMonitor
  max_epochs: 200
  precision: 16
  detect_anomaly: true
data:
  class_path: cmap.data.modules.SQLDataModule
  init_args:
    database_url: postgresql+psycopg2://michel:cmap2023@localhost:6666/crops 
    sample:  true
    fraction: 0.3 
    num_workers: 8
    chunk_size: 16
    batch_size: 128 
    train_seasons:
      - 2019
      - 2020
    val_seasons:
      - 2021 
    classes:
      - other
      - ble_dur
      - ble_tendre
      - mais
      - orge
      - colza
      - tournesol
model:
  class_path: cmap.ml.classifiers.Classifier
  init_args:
    encoder:
      class_path : cmap.ml.encoders.TransformerEncoder
      init_args:
        position_encoder:
          class_path : cmap.ml.embeddings.position.PositionalEncoding
          init_args:
            d_model: 256
            tau : 10000.0
            max_len: 10000
        bands_encoder:
          class_path : cmap.ml.embeddings.bands.PatchBandsEncoding
          init_args:
            channels:
              - 32
              - 64
              - 256
            kernels:
              - 5
              - 5
        n_att_head: 8
        n_att_layers: 4
        dropout_p: 0.1
    decoder:
      class_path: cmap.ml.decoders.MulticlassClassification      
      init_args:
        hidden: 256 
        num_classes: 7
    min_lr : 0.00001
    max_lr : 0.0001
    class_weights:
      other: 0.03
      ble_tendre: 0.03
      ble_dur : 0.57
      mais : 0.04
      orge: 0.05
      colza : 0.11
      tournesol: 0.17
