trainer:
  callbacks: pytorch_lightning.callbacks.LearningRateMonitor
  max_epochs: 100
data:
  data_root: /mnt/sda/geowatch/datasets/hackathon/crop_mapping/fra_23_tiles_sorted
  num_workers: 32
  batch_size: 512
  records_frac : 0.1
  classes:
    - other
    - ble_dur
    - ble_tendre
    - orge
    - colza
    - mais
    - tournesol
model:
  n_bands: 9
  max_n_days : 397
  d_model : 256 
